import './globals.css';
import Footer from '../components/Layout/Footer';
import Header from '../components/Layout/Header';

export const metadata = {
  title: 'CFC - Máximo Paz',
  description: 'CFC - Máximo Paz',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Create Wix Education Site</title>
        <meta
          name="description"
          content="Generated by create next app with Wix Education integration"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://www.wix.com/favicon.ico" />
      </head>
      <body className="text-violeta bg-white">
        <>
          <Header />
          <main className="bg-white min-h-[600px] mt-16">{children}</main>
          <div className="mt-10 sm:mt-20">
            <Footer />
          </div>
        </>
      </body>
    </html>
  );
}
